### PR TITLE
Forwarding i64/u64 serialization to serde

### PR DESCRIPTION
**Pull request by osiewers**
Aims to implement #21. I am not sure if the serde dependency version has to be updated tho...

### CODE REVIEW

**Comment by RReverser** [comment]
I'm not sure this works the way you think it does (producing bigints), but happy to be proven wrong. Can you add tests that check that the resulting value is indeed a `bigint`?

Also, the deserialization part is missing.

**Comment by osiewers** [comment]
I have no idea how to actually do the deserialization part, but I'll try to take a look. Tested it in my local environment and at least on the browser side I got `bigint`s (tested using `console.log`). I'll come back in a few days, currently I got lots of work to do.

**Comment by RReverser** [comment]
The tests seem to fail too. Please test with `wasm-pack test` locally while you're working on the PR.

**Comment by osiewers** [comment]
Will do, thanks!

**Comment by RReverser** [comment]
> I have no idea how to actually do the deserialization part, but I'll try to take a look.

I mentioned how to do that with some links in a comment on the issue yesterday.

**Comment by osiewers** [comment]
> I mentioned how to do that with some links in a comment on the issue yesterday.

Yes, I know, but since I've absolutely no clue how to do rust the right way (I'm a C/C++/Go guy) I'll need some time to figure things out ;)

**Comment by RReverser** [comment]
One more thing - the change of `serialize_{i,u}64` to produce BigInts instead of the previous behaviour (safe numbers) would be a breaking change; I suspect that might be why the tests are failing too.

We'd probably want either a serialization option or a major bump to accomodate such change.

**Comment by osiewers** [comment]
I'm really really busy with work at the moment, was hoping to find some time on a weekend but I don't think it's going to happen anytime soon, so if somebody want's to take over it'd be appreciated. Otherwise I'll continue to work on this once I got a little more spare time on my hand.

**Pull request closed without merging**
